<?php

use Violeta\SpecialOffer\Block\SpecialOffer;

$config = $block->getConfigArray();
$content = $block->getLayout()
    ->createBlock('Magento\Cms\Block\Block')
    ->setBlockId(SpecialOffer::POP_BLOCK_IDENTIFIER)
    ->toHtml();
?>

<?php if ($config['enable'] && !empty($content)): ?>
    <div id="popup-modal" style="display: none">
        <h1><?php echo $content ?></h1>
    </div>
    <script>
        require(
            [
                'jquery',
                'Magento_Ui/js/modal/modal'
            ],
            function (
                $,
                modal
            ) {
                let delay = <?php echo $config['delay'] ?>;
                let title = '<?php echo $config['title'] ?>';
                setTimeout(function () {
                    let options = {
                        type: 'popup',
                        responsive: true,
                        innerScroll: true,
                        title: title,
                        buttons: [{
                            text: $.mage.__('Close'),
                            class: '',
                            click: function () {
                                this.closeModal();
                            }
                        }]
                    };
                    let popup = modal(options, $('#popup-modal'));
                    $('#popup-modal').modal('openModal');
                }, delay * 1000);
            }
        );
    </script>
<?php endif; ?>
